# Generated by Django 4.2.23 on 2025-06-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='是否已完成'),
        ),
    ]
