# Generated by Django 5.2.1 on 2025-06-30 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_project'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_user_id_8193d6_idx',
            old_name='chat_convers_user_id_project_id_updated_at_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_project_a83b6f_idx',
            old_name='chat_convers_project_id_updated_at_idx',
        ),
    ]
