# Generated by Django 5.2 on 2025-06-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_services", "0002_aitasklog_document_aitasklog_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="max_tokens",
            field=models.PositiveIntegerField(default=10000, verbose_name="最大令牌数"),
        ),
        migrations.AlterField(
            model_name="aitasklog",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("chat", "智能对话"),
                    ("quiz", "测验生成"),
                    ("summary", "文档总结"),
                    ("query_rewrite", "查询重写"),
                    ("conversation_summary", "对话历史摘要"),
                    ("chat_fix", "聊天输出修复"),
                    ("quiz_fix", "测验输出修复"),
                    ("summary_fix", "摘要输出修复"),
                ],
                max_length=20,
                verbose_name="任务类型",
            ),
        ),
    ]
