# Generated by Django 5.2 on 2025-06-01 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="测验标题")),
                ("description", models.TextField(blank=True, verbose_name="测验描述")),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "简单"),
                            ("medium", "中等"),
                            ("hard", "困难"),
                            ("master", "大师"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="难度级别",
                    ),
                ),
                (
                    "total_questions",
                    models.PositiveIntegerField(default=0, verbose_name="题目总数"),
                ),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="生成配置"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="documents.document",
                        verbose_name="关联文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "测验",
                "verbose_name_plural": "测验",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="题目内容")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MC", "单选题"),
                            ("MCM", "多选题"),
                            ("TF", "判断题"),
                            ("FB", "填空题"),
                            ("SA", "简答题"),
                        ],
                        max_length=3,
                        verbose_name="题目类型",
                    ),
                ),
                (
                    "options",
                    models.JSONField(blank=True, null=True, verbose_name="选项"),
                ),
                ("correct_answer", models.JSONField(verbose_name="正确答案")),
                ("explanation", models.TextField(verbose_name="解释说明")),
                (
                    "source_passage",
                    models.TextField(blank=True, verbose_name="来源段落"),
                ),
                (
                    "knowledge_points",
                    models.JSONField(blank=True, default=list, verbose_name="知识点"),
                ),
                ("difficulty", models.IntegerField(default=1, verbose_name="难度")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quiz.quiz",
                        verbose_name="所属测验",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目",
                "verbose_name_plural": "题目",
                "ordering": ["quiz", "order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answers", models.JSONField(default=dict, verbose_name="答案记录")),
                ("score", models.FloatField(default=0.0, verbose_name="得分")),
                ("total_score", models.FloatField(default=0.0, verbose_name="总分")),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="答题时长"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="quiz.quiz",
                        verbose_name="测验",
                    ),
                ),
            ],
            options={
                "verbose_name": "答题记录",
                "verbose_name_plural": "答题记录",
                "ordering": ["-start_time"],
            },
        ),
    ]
