# Generated by Django 5.2.1 on 2025-06-16 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='生成此测验的源文档', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document', verbose_name='源文档'),
        ),
    ]
