# Generated by Django 5.2.1 on 2025-06-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_source_document_question_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='元数据'),
        ),
    ]
