# Generated by Django 5.2 on 2025-06-01 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="对话标题"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("chat", "聊天模式"),
                            ("summary", "总结模式"),
                            ("quiz", "测验模式"),
                        ],
                        default="chat",
                        max_length=20,
                        verbose_name="交互模式",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="对话上下文"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="documents.document",
                        verbose_name="关联文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "对话会话",
                "verbose_name_plural": "对话会话",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "is_user",
                    models.BooleanField(default=True, verbose_name="是否为用户消息"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "feedback_score",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "差"),
                            (2, "一般"),
                            (3, "好"),
                            (4, "很好"),
                            (5, "优秀"),
                        ],
                        null=True,
                        verbose_name="反馈评分",
                    ),
                ),
                (
                    "feedback_comment",
                    models.TextField(blank=True, verbose_name="反馈评论"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                        verbose_name="所属对话",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息",
                "verbose_name_plural": "消息",
                "ordering": ["conversation", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("document", "文档"), ("chunk", "文档片段")],
                        default="document",
                        max_length=20,
                        verbose_name="来源类型",
                    ),
                ),
                ("source_id", models.PositiveIntegerField(verbose_name="来源ID")),
                ("source_content", models.TextField(verbose_name="来源内容")),
                (
                    "relevance_score",
                    models.FloatField(default=0.0, verbose_name="相关性评分"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="chat.message",
                        verbose_name="关联消息",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息来源",
                "verbose_name_plural": "消息来源",
                "ordering": ["-relevance_score"],
            },
        ),
    ]
